name: Calculator
author: abidibo
category: Widgets
tags: [calculator, math, widget]
docs: http://www.abidibo.net/projects/js/calculator
demo: http://www.abidibo.net/projects/js/calculator/demo
current: 0.1
